### PR TITLE
Update selection label on change

### PR DESCRIPTION
**Pull request by aluink**

### CODE REVIEW

**Comment by btecu** [comment]
`oldValue && newValue` doesn't make sense anymore, since it was only used to safely access `value`.

**Comment by aluink** [comment]
Ahh yes, though we still need to check newValue as it's still used.  Correct?

**Comment by btecu** [comment]
No, you always have `newValue`.
However, `attrs` argument is private and it's getting deprecated
http://emberjs.com/deprecations/v2.x/#toc_arguments-in-component-lifecycle-hooks

So, it would be better to just look at the value (`this.get('value')`).

**Comment by btecu** [comment]
Fixed in `0.3.0` (https://github.com/btecu/ember-select/commit/cba60467ce0ee7940be2cdbb42070cdaf28d5b64).

**Pull request closed without merging**
